import React from 'react';
import type { Metadata } from 'next';
import { ThemeModeProvider } from '@sigma-ui-kit/theme';

import { Providers } from './provider';
import Header from './components/Header';

import './globals.css';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeModeProvider defaultThemeMode="system" enableSystem disableTransitionOnChange>
          <Providers>
            <div>
              <Header />
              <main>{children}</main>
            </div>
          </Providers>
        </ThemeModeProvider>
      </body>
    </html>
  );
}
