// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Components = Collections['components']['schema']['_output']
export declare const components: Components[]

export type Guides = Collections['guides']['schema']['_output']
export declare const guides: Guides[]

export type Theming = Collections['theming']['schema']['_output']
export declare const theming: Theming[]
