import { TokensConfig } from '@sigma-ui-kit/theme';

const tabletTokens: TokensConfig = {
  radii: {
    default: '4px',
    xs: '2px',
    md: '8px',
    lg: '16px',
    xl: '32px',
    '2xl': '64px',
  },
  fontSizes: {
    'text-xxs': '12px',
    'text-xs': '14px',
    'text-sm': '16px',
    'text-md': '18px',
    'text-lg': '20px',
    'text-xl': '24px',
    'display-xs': '28px',
    'display-sm': '32px',
    'display-md': '40px',
    'display-lg': '48px',
    'display-xl': '60px',
    'display-2xl': '72px',
  },
  lineHeights: {
    'text-xxs': '18px',
    'text-xs': '20px',
    'text-sm': '24px',
    'text-md': '28px',
    'text-lg': '30px',
    'text-xl': '32px',
    'display-xs': '38px',
    'display-sm': '44px',
    'display-md': '48px',
    'display-lg': '60px',
    'display-xl': '72px',
    'display-2xl': '90px',
  },
  icons: {
    size: {
      xxxs: '16px',
      xxs: '18px',
      xs: '20px',
      sm: '24px',
      md: '28px',
      lg: '32px',
      xl: '40px',
    },
  },
  buttons: {
    height: {
      smallest: '28px',
      smaller: '32px',
      small: '36px',
      medium: '40px',
      standard: '44px',
      big: '56px',
      bigger: '64px',
      biggest: '72px',
    },
    spacing: {
      smaller: '6px',
      small: '8px',
      standard: '10px',
      big: '12px',
      bigger: '16px',
    },
    paddingHorizontal: {
      smallest: '8px',
      smaller: '10px',
      small: '12px',
      standard: '16px',
      big: '20px',
      bigger: '24px',
      biggest: '32px',
    },
    paddingVertical: {
      smallest: '6px',
      smaller: '8px',
      small: '10px',
      standard: '12px',
      big: '14px',
      bigger: '16px',
      biggest: '20px',
    },
    radii: {
      smallest: '6px',
      smaller: '8px',
      small: '10px',
      standard: '12px',
      big: '16px',
      bigger: '20px',
      biggest: '24px',
    },
  },
};

export default tabletTokens;
