import { TokensConfig } from '@sigma-ui-kit/theme';

const desktopTokens: TokensConfig = {
  radii: {
    xs: '2px',
    sm: '4px',
    md: '8px',
    lg: '16px',
    xl: '32px',
    '2xl': '64px',
    rounded: '9999px',
  },
  fontSizes: {
    'text-xxs': '10px',
    'text-xs': '12px',
    'text-sm': '14px',
    'text-md': '16px',
    'text-lg': '18px',
    'text-xl': '20px',
    'display-xs': '24px',
    'display-sm': '30px',
    'display-md': '36px',
    'display-lg': '48px',
    'display-xl': '60px',
    'display-2xl': '72px',
  },
  lineHeights: {
    'text-xxs': '16px',
    'text-xs': '18px',
    'text-sm': '20px',
    'text-md': '24px',
    'text-lg': '28px',
    'text-xl': '30px',
    'display-xs': '32px',
    'display-sm': '38px',
    'display-md': '44px',
    'display-lg': '60px',
    'display-xl': '72px',
    'display-2xl': '90px',
  },
  icons: {
    size: {
      xxxs: '14px',
      xxs: '16px',
      xs: '18px',
      sm: '20px',
      md: '24px',
      lg: '28px',
      xl: '32px',
    },
  },
  buttons: {
    height: {
      smallest: '24px',
      smaller: '28px',
      small: '32px',
      medium: '36px',
      standard: '40px',
      big: '48px',
      bigger: '56px',
      biggest: '64px',
    },
    spacing: {
      smaller: '6px',
      small: '8px',
      standard: '10px',
      big: '12px',
      bigger: '16px',
    },
    paddingHorizontal: {
      smallest: '6px',
      smaller: '8px',
      small: '10px',
      standard: '12px',
      big: '16px',
      bigger: '20px',
      biggest: '24px',
    },
    paddingVertical: {
      smallest: '4px',
      smaller: '6px',
      small: '8px',
      standard: '10px',
      big: '12px',
      bigger: '14px',
      biggest: '16px',
    },
    radii: {
      smallest: '4px',
      smaller: '6px',
      small: '8px',
      standard: '10px',
      big: '12px',
      bigger: '16px',
      biggest: '20px',
    },
  },
};

export default desktopTokens;
